### PR TITLE
Fix migration context usage in some rails 6 versions

### LINKED ISSUE #2: Can't launch with latest Rails version
Hey Jesse, I tried running `LazyMigration.run` with rails `6.0.3.2` and I hit this error:

> ArgumentError: wrong number of arguments
> from ~.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1028:in `initialize'

I assume it comes from this line:
https://github.com/jesseduffield/lazy_migrate/blob/498c66273c9111380a0937ec6718c39bde043864/lib/lazy_migrate/new_migrator_adapter.rb#L18

And is a consequence of this change https://github.com/rails/rails/commit/7cc27d749c3563e6b278ad01d233cb92ea3b7935#diff-8d3c44120f7b67ff79e2fbe6a40d0ad6R1018

### PR DESCRIPTION
**Pull request by PikachuEXE**
Fixes #2

Missing tests though
I have no idea how to test against rails 6 in spec

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Added GitHub Action config for CI
But it might require manual update on project setting to enable running spec on GH Action

**Comment by jesseduffield** [comment]
@PikachuEXE thanks for making this! Sorry that I haven't reviewed it yet I've been flat out but I'll try my best to find the time today

**Comment by PikachuEXE** [comment]
Yup we are all busy
Take your time~

**Comment by PikachuEXE** [comment]
[rails 6.1 rc2 is out](https://weblog.rubyonrails.org/2020/12/4/this-week-in-rails-rails-6-1-rc2-and-some-enhancements/)

**Comment by PikachuEXE** [comment]
@jesseduffield 
[rails 6.1 is out already~](https://weblog.rubyonrails.org/2020/12/9/Rails-6-1-0-release/) 🤣

**Comment by PikachuEXE** [comment]
@jesseduffield 
Reminder to review this PR when available 🙏

**Comment by jesseduffield** [comment]
@PikachuEXE thankyou for your patience! I have been very bad at staying on top of this. At any rate I've taken a look at the code and it looks good. I'll do a quick test now

**Comment by jesseduffield** [comment]
hmm so it works locally but looks like it fails on CI now

**Comment by jesseduffield** [comment]
All good I fixed CI in https://github.com/jesseduffield/lazy_migrate/pull/7.

Thanks again for making this!

**Pull request merged**
